workflows:
  main:
    name: Build and deploy web
    instance_type: linux
    environment:
      # 和你本地一致，比如你本地是 3.22.2 就写这个
      flutter: 3.22.2
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build web
        script: flutter build web --release
    artifacts:
      - build/web/**
    publishing:
      codemagic_static_pages:
        enabled: true
        subdomain: troll-flutter-demo-2026
